apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dwbconsultingllc/intro-to-argo" # Update to match your fork.
    path: portal
    targetRevision: HEAD
  destination:
    namespace: portal
    name: kind # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
